document.addEventListener('DOMContentLoaded', function() {
    const websiteUrlInput = document.getElementById('websiteUrl');
    const allowAllCheckbox = document.getElementById('allowAll');
    const disallowAllCheckbox = document.getElementById('disallowAll');
    const customRulesTextarea = document.getElementById('customRules');
    const sitemapUrlInput = document.getElementById('sitemapUrl');
    const crawlDelayInput = document.getElementById('crawlDelay');
    const generateBtn = document.getElementById('generateBtn');
    const copyBtn = document.getElementById('copyBtn');
    const downloadBtn = document.getElementById('downloadBtn');
    const robotsOutput = document.getElementById('robotsOutput');

    function generateRobotsTxt() {
        const websiteUrl = websiteUrlInput.value.trim();
        if (!websiteUrl) {
            alert('Please enter your website URL');
            return;
        }

        let robotsContent = '# robots.txt generated by Free Tools Hub\n';
        robotsContent += `# Website: ${websiteUrl}\n`;
        robotsContent += `# Generated on: ${new Date().toISOString().split('T')[0]}\n\n`;

        robotsContent += 'User-agent: *\n';

        if (allowAllCheckbox.checked) {
            robotsContent += 'Allow: /\n';
        } else if (disallowAllCheckbox.checked) {
            robotsContent += 'Disallow: /\n';
        } else {
            // Default rules
            robotsContent += 'Allow: /\n';
            robotsContent += 'Disallow: /admin/\n';
            robotsContent += 'Disallow: /private/\n';
            robotsContent += 'Disallow: /temp/\n';
        }

        // Add custom rules
        const customRules = customRulesTextarea.value.trim();
        if (customRules) {
            robotsContent += '\n# Custom rules\n';
            robotsContent += customRules + '\n';
        }

        // Add crawl delay
        const crawlDelay = crawlDelayInput.value.trim();
        if (crawlDelay && crawlDelay > 0) {
            robotsContent += `\nCrawl-delay: ${crawlDelay}\n`;
        }

        // Add sitemap
        const sitemapUrl = sitemapUrlInput.value.trim();
        if (sitemapUrl) {
            robotsContent += `\nSitemap: ${sitemapUrl}\n`;
        } else if (websiteUrl) {
            const baseUrl = websiteUrl.replace(/\/$/, '');
            robotsContent += `\nSitemap: ${baseUrl}/sitemap.xml\n`;
        }

        robotsOutput.textContent = robotsContent;
        robotsOutput.style.display = 'block';
        copyBtn.style.display = 'inline-block';
        downloadBtn.style.display = 'inline-block';
    }

    function copyToClipboard() {
        robotsOutput.select();
        document.execCommand('copy');
        
        const originalText = copyBtn.textContent;
        copyBtn.textContent = 'Copied!';
        setTimeout(() => {
            copyBtn.textContent = originalText;
        }, 2000);
    }

    function downloadRobotsTxt() {
        const content = robotsOutput.textContent;
        const blob = new Blob([content], { type: 'text/plain' });
        const url = window.URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = 'robots.txt';
        link.click();
        window.URL.revokeObjectURL(url);
    }

    // Event listeners
    generateBtn.addEventListener('click', generateRobotsTxt);
    copyBtn.addEventListener('click', copyToClipboard);
    downloadBtn.addEventListener('click', downloadRobotsTxt);

    // Mutual exclusion for checkboxes
    allowAllCheckbox.addEventListener('change', function() {
        if (this.checked) {
            disallowAllCheckbox.checked = false;
        }
    });

    disallowAllCheckbox.addEventListener('change', function() {
        if (this.checked) {
            allowAllCheckbox.checked = false;
        }
    });

    // Set placeholder values
    websiteUrlInput.placeholder = 'https://example.com';
    sitemapUrlInput.placeholder = 'https://example.com/sitemap.xml';
    customRulesTextarea.placeholder = 'Disallow: /admin/\nDisallow: /private/\nAllow: /public/';
});